insert into person (first_name, last_name, age) values
('David', 'Beckham', 45),
('Ryan', 'Giggs', 47),
('Paul', 'Scholes', 46),
('Eric', 'Cantona', 54),
('George', 'Best', 74),
('Bobby', 'Charlton', 83),
('Wayne', 'Rooney', 35),
('Cristiano', 'Ronaldo', 36),
('Ole', 'Gunnar Solskjaer', 48),
('Roy', 'Keane', 49),
('Gary', 'Neville', 46),
('Kai', 'Rooney', 11),
('Nemanja', 'Vidic', 39),
('Rio', 'Ferdinand', 42),
('Edwin', 'Van Der Sar', 50),
('Peter', 'Schmeichel', 57),
('Denis', 'Irwin', 55),
('Jaap', 'Stam', 48),
('Andy', 'Cole', 49),
('Dwight', 'Yorke', 49),
('Ruud', 'Van Nistelrooy', 44),
('Robin', 'Van Persie', 37),
('Michael', 'Carrick', 39),
('Patrice', 'Evra', 39),
('Antonio', 'Valencia', 35),
('David', 'De Gea', 30),
('Marcus', 'Rashford', 23),
('Mason', 'Greenwood', 19),
('Bruno', 'Fernandes', 26),
('Harry', 'Maguire', 28),
('Luke', 'Shaw', 25),
('Aaron', 'Wan-Bissaka', 23),
('Victor', 'Lindelof', 26),
('Axel', 'Tuanzebe', 23),
('Dean', 'Henderson', 24),
('Scott', 'McTominay', 24),
('Fred', 'Rodrigues', 27),
('Donny', 'Van De Beek', 24),
('Jesse', 'Lingard', 28),
('Juan', 'Mata', 33),
('Daniel', 'James', 23),
('Anthony', 'Martial', 25),
('Edinson', 'Cavani', 37),
('Alejandro', 'Garnacho', 19),
('Rasmus', 'Hojlund', 20),
('Kobbie', 'Mainoo', 18)